# Alpine Linux netboot cmdline
# Embedded in alpine-netboot.efi UKI

modloop=https://dl-cdn.alpinelinux.org/alpine/edge/releases/x86_64/netboot/modloop-lts
alpine_repo=https://dl-cdn.alpinelinux.org/alpine/edge/main
ip=dhcp
console=tty0
console=ttyS0,115200n8
