# Flatcar Container Linux network pull cmdline
# Embedded in flatcar.efi UKI

rd.systemd.pull=raw,machine,verify=no,blockdev:flatcar:https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_image.bin.bz2
root=gpt-auto
ip=dhcp
console=tty0
console=ttyS0,115200n8
systemd.log_level=info
