# VyOS 1.5 Rolling network boot cmdline
# Embedded in vyos.efi UKI
#
# NOTE: The VyOS URL below contains a specific rolling build date and will become outdated quickly.
# IMPORTANT: You MUST update the URL below regularly to use the latest rolling build.
# Get the latest build URL from:
# https://github.com/vyos/vyos-rolling-nightly-builds/releases/
boot=live
fetch=https://github.com/vyos/vyos-rolling-nightly-builds/releases/download/1.5-rolling-202501200023/vyos-1.5-rolling-202501200023-amd64.iso
ip=dhcp
console=tty0
console=ttyS0,115200
